Models:
  model_0:
    name: "GPT-4o-mini-temp-0"
    profile_result: 
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/GPT-4o-mini-temp-0"
  model_1:
    name: "Qwen3-14B-temp-0-en-thinking"
    profile_result:
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-14B-temp-0-en-thinking"
Benchmarks:
  GSM8K: "/home/ouyk/project/ICDCS/Oracle/profile/GSM8K/data/train.jsonl"
Output:
  path: "./output"