Models:
  model_0:
    name: "Deepseek-v3.2-Exp-temp-0-reasoner"
    profile_result: 
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Deepseek-v3.2-Exp-temp-0-reasoner"
  model_1:
    name: "Qwen3-0.6B-temp-0-en-thinking"
    profile_result:
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-0.6B-temp-0-en-thinking"
Benchmarks:
  GSM8K: "/home/ouyk/project/ICDCS/Oracle/profile/GSM8K/data/train.jsonl"
Output:
  path: "./output"