Models:
  model_0:
    name: "Deepseek-v3.2-Exp-temp-0-reasoner"
    profile_result: 
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Deepseek-v3.2-Exp-temp-0-reasoner"
  model_1:
    name: "Qwen3-14B-temp-0-no-thinking"
    profile_result:
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-14B-temp-0-no-thinking"
  model_2:
    name: "Qwen3-0.6B-temp-0-no-thinking"
    profile_result:
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-0.6B-temp-0-no-thinking"
Benchmarks:
  GSM8K: "/home/ouyk/project/ICDCS/Oracle/profile/GSM8k/grade-school-math/grade_school_math/data/train.jsonl"
Output:
  path: "./output"