Models:
  model_0:
    name: "Qwen3-0.6B-temp-0-no-thinking"
    profile_result: 
      GSM8K: "/Users/quao/Desktop/Second-year/ICDCS/repo/Oracle/input/GSM8K/Qwen3-0.6B-temp-0-no-thinking"
  model_1:
    name: "Qwen3-14B-temp-0-no-thinking"
    profile_result:
      GSM8K: "/Users/quao/Desktop/Second-year/ICDCS/repo/Oracle/input/GSM8K/Qwen3-14B-temp-0-no-thinking"
Benchmarks:
  GSM8K: "/Users/quao/Desktop/Second-year/ICDCS/repo/Oracle/input/GSM8K/train.jsonl"
Output:
  path: "./output"