Models:
  model_0:
    name: "o4-mini-temp-1"
    profile_result: 
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/o4-mini-temp-1"
  model_1:
    name: "Qwen3-0.6B-temp-0-no-thinking"
    profile_result:
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-0.6B-temp-0-no-thinking"
Benchmarks:
  GSM8K: "/home/ouyk/project/ICDCS/Oracle/profile/GSM8k/grade-school-math/grade_school_math/data/train.jsonl"
Output:
  path: "./output"