Data:
  benchmark: "Chatbot-Arena"
  data_dir: "/home/ouyk/project/ICDCS/Oracle/input/Chatbot-Arena"
  num_data: 2586
  embeddings_dir: /home/ouyk/project/ICDCS/Oracle/input/Embeddings/
  labels:
    num_tokens_range_split: 16
Models:
  KNN:
    n_neighbors: 5
  MLP: