Data:
  benchmark: "GSM8K"
  data_dir: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K"
  num_data: 7473
  embeddings_dir: /home/ouyk/project/ICDCS/Oracle/input/Embeddings/
  labels:
    num_tokens_range_split: 20
Models:
  KNN:
    n_neighbors: 5
  MLP: