Models:
  model_0:
    name: "Qwen3-14B-temp-0-no-thinking"
    profile_result: 
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-14B-temp-0-no-thinking"
  model_1:
    name: "Qwen3-0.6B-temp-0-no-thinking"
    profile_result:
      GSM8K: "/home/ouyk/project/ICDCS/Oracle/input/GSM8K/Qwen3-0.6B-temp-0-no-thinking"
Benchmarks:
  GSM8K: "/home/ouyk/project/ICDCS/Oracle/profile/GSM8K/data/train.jsonl"
Output:
  path: "./output"